name: "Documentation"
on:
  push:
    branches:
      - "main"
    tags: "*"
  pull_request: ~
  schedule:
    - cron: "1 4 * * 4"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: "${{ github.ref_name != github.event.repository.default_branch || github.ref != 'refs/tags/v*' }}"
jobs:
  build-and-deploy-docs:
    name: "Documentation"
    uses: "ITensor/ITensorActions/.github/workflows/Documentation.yml@main"
    with:
      localregistry: "https://github.com/ITensor/ITensorRegistry.git"
      apt-packages: "xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev"
      doc-prefix: "xvfb-run -a -s '-screen 0 1024x768x24' "
    secrets:
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
